name: DART commons publish

on:
  push:
    branches: [ DART-1314-adding-github-actions ]
  pull_request:
    branches: [ DART-1314-adding-github-actions ]

jobs:
  publish-to-sonatype:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Tag a release
        uses: ./github/actions/tag-release

#      - name: Publishing to Sonatype
#        run: sbt ci-release
#        env:
#          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
#          PGP_SECRET: ${{ secrets.PGP_SECRET }}
#          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
#          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
